import type { NextPage } from 'next'
import Head from 'next/head'
import Menu from '@components/layout/menu'
import { MenuItemProps } from '@components/layout/menu/interface'
import ThemeHandler from '@components/layout/themeHandler'

const Itens: NextPage = () => {
  const menuData: MenuItemProps[] = [
    {
      label: "Opção 1",
      icon: "a",
      route: "home",
    },
    {
      label: "Opção 2",
      icon: "a",
      route: "home1",
    },
    {
      label: "Opção 3",
      icon: "a",
      route: "home2",
    },
    {
      label: "Opção 4",
      icon: "a",
      route: "home3",
    },
    {
      label: "Opção 5",
      icon: "a",
      route: "home4",
    },
    // {
    //   label: "Opção 6",
    //   icon: "a",
    //   route: "home5",
    // },
    // {
    //   label: "Opção 7",
    //   icon: "a",
    //   route: "home6",
    // },
    // {
    //   label: "Opção 8",
    //   icon: "a",
    //   route: "home7",
    // },
    // {
    //   label: "Opção 9",
    //   icon: "a",
    //   route: "home8",
    // },
  ]

  return (
    <div>
      <Head>
        <title>Itens</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu data={menuData} />
      <ThemeHandler/>
    </div>
  )
}

export default Itens
